server:
  port: 8521

spring:
  profiles: test

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db_wanjiale?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    dbcp2:
      min-idle: 10
      initial-size: 10
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
      connection-init-sqls: set names utf8mb4

    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

#  #redis配置信息
#  redis:
#    database: 0
#    host: 39.98.138.221
#    password:
#    port: 8508
#    timeout: 5000
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#
#  elasticsearch:
#    rest:
#      uris: 39.98.138.221:8510
#      #多媒体系统地址:47.93.185.66:9400
#      #博客大数据系统地址:39.98.138.221:8510
#
#logging:
#    level:
#      com:
#        example:
#          blogBigDataSystem:
#            mapper : debug
