server:
  port: 8072

spring:
  profiles: prod

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

#  #redis配置信息
#  redis:
#    database: 0
#    host: 172.17.75.6
#    password: ayjZO@9YLeoW
#    port: 6379
#    timeout: 5000
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#
#  elasticsearch:
#    rest:
#      uris: 172.17.75.6:9201
#
#logging:
#  level:
#    com:
#      example:
#        blogBigDataSystem:
#          mapper : debug